name: 'cron-holiday'
description: 'Prevents scheduled workflows from running on specified holidays.'
author: '@lowlydba'
branding:
  icon: 'calendar'
  color: 'gray-dark'

inputs:
  holidays:
    description: 'Comma-separated list of YYYY-MM-DD holiday dates (e.g., 2025-01-01,2025-07-04)'
    required: true

  timezone:
    description: 'IANA timezone (e.g., America/New_York). Defaults to UTC.'
    required: false
    default: 'UTC'

  fail-on-holiday:
    description: 'If true, the step will fail when today is a holiday.'
    required: false
    default: 'false'

outputs:
  on_holiday:
    description: 'true if today is a holiday, false otherwise'
    value: ${{ steps.check_holiday.outputs.on_holiday }}

runs:
  using: 'composite'
  steps:

    - shell: bash
      id: check_holiday
      run: |
        bash ./check_holiday.sh "${{ inputs.timezone }}" "${{ inputs.holidays }}" "${{ inputs.fail-on-holiday }}"
