name: E2E Test - Should Skip on Holiday
on:
  workflow_dispatch:
  push:

jobs:
  check-holiday:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run cron-holiday (should skip)
        id: holiday
        uses: ./
        with:
          holidays: "2025-05-27"
          timezone: "UTC"
          fail-on-holiday: false
      - name: Should not run on holiday
        if: ${{ steps.holiday.outputs.on_holiday != 'true' }}
        run: |
          echo "This should NOT run on 2025-05-27!"
      - name: Assert skipped
        run: |
          if [ "${{ steps.holiday.outputs.on_holiday }}" != "true" ]; then
            echo "❌ Did not detect holiday correctly!" && exit 1
          else
            echo "✅ Correctly detected holiday."
          fi
