name: E2E Test - Skip On Holiday
on:
  workflow_dispatch:
  push:

jobs:
  check-skip-on-holiday:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get today's date
        id: date
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Run cron-holiday (skip on holiday)
        id: holiday
        uses: ./
        with:
          holidays: "${{ steps.date.outputs.today }}"
          timezone: "UTC"
          fail-on-holiday: true
      - name: Assert skipped
        run: |
          if [ "${{ steps.holiday.outputs.on_holiday }}" != "true" ]; then
            echo "❌ Did not skip on holiday as expected!" && exit 1
          else
            echo "✅ Correctly skipped on holiday."
          fi
