name: E2E Test - Invalid Timezone
on:
  workflow_dispatch:
  push:

jobs:
  check-invalid-timezone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get today's date
        id: date
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Run cron-holiday with invalid timezone
        id: holiday
        continue-on-error: true
        uses: ./
        with:
          holidays: "2025-01-01,${{ steps.date.outputs.today }}"
          timezone: "NotAReal/Timezone"
          fail-on-holiday: false
      - name: Assert failure on invalid timezone
        run: |
          if [ "${{ steps.holiday.outcome }}" = "success" ]; then
            echo "❌ The workflow did not fail as expected for an invalid timezone!"
            exit 1
          else
            echo "✅ Workflow failed as expected for an invalid timezone."
          fi
