name: E2E Test - Holidays With Spaces
on:
  workflow_dispatch:
  push:

jobs:
  check-holidays-with-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run cron-holiday (holidays with spaces)
        id: holiday
        uses: ./
        with:
          holidays: "2025-01-01, 2025-05-27, 2025-12-25"
          timezone: "UTC"
          fail-on-holiday: false
      - name: Should not run on holiday
        if: ${{ steps.holiday.outputs.on_holiday != 'true' }}
        run: |
          echo "This should NOT run on 2025-05-27!"
      - name: Assert skipped
        run: |
          if [ "${{ steps.holiday.outputs.on_holiday }}" != "true" ]; then
            echo "❌ Did not detect holiday correctly with spaces!" && exit 1
          else
            echo "✅ Correctly detected holiday with spaces."
          fi
