name: E2E Test - Should Run on Non-Holiday
on:
  workflow_dispatch:
  push:

jobs:
  check-holiday:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get today's date
        id: date
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Run cron-holiday (run on non-holiday)
        id: holiday
        uses: ./
        with:
          holidays: "2025-01-01,2025-12-25"
          timezone: "UTC"
          fail-on-holiday: false
      - name: Assert not skipped
        run: |
          if [ "${{ steps.holiday.outputs.on_holiday }}" = "true" ]; then
            echo "❌ Incorrectly detected today as a holiday!" && exit 1
          else
            echo "✅ Correctly did not detect today as a holiday."
          fi
