name: E2E Test - Multiple Holidays
on:
  workflow_dispatch:
  push:

jobs:
  check-multiple-holidays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get today's date
        id: date
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Run cron-holiday (multiple holidays)
        id: holiday
        uses: ./
        with:
          holidays: "2025-01-01,${{ steps.date.outputs.today }},2025-12-25"
          timezone: "UTC"
          fail-on-holiday: false
      - name: Should not run on holiday
        if: ${{ steps.holiday.outputs.on_holiday != 'true' }}
        run: |
          echo "This should NOT run on ${{ steps.date.outputs.today }}!"
      - name: Assert skipped
        run: |
          if [ "${{ steps.holiday.outputs.on_holiday }}" != "true" ]; then
            echo "❌ Did not detect holiday correctly from multiple holidays!" && exit 1
          else
            echo "✅ Correctly detected holiday from multiple holidays."
          fi
